# Generated by Django 4.2.7 on 2025-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("sale", "For Sale"),
                    ("rent", "For Rent"),
                    ("lease", "Lease"),
                    ("pg", "Paying Guest"),
                ],
                max_length=10,
            ),
        ),
    ]
