# Generated by Django 4.2.7 on 2025-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0002_alter_property_options_property_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Property Owner"),
                    ("seeker", "Property Seeker"),
                    ("admin", "Administrator"),
                ],
                max_length=10,
            ),
        ),
    ]
