# Generated by Django 5.0.1 on 2025-05-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Property Owner"),
                    ("seeker", "Property Seeker"),
                    ("admin", "Administrator"),
                ],
                default="seeker",
                max_length=10,
            ),
        ),
    ]
